=== MER1GO/MER1GO.github.io/sites/nure/lb5/blog.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="blog">
   <xs:complexType>
      <xs:sequence>
      	<xs:element name="post">
   			<xs:complexType>
      			<xs:sequence>
			        <xs:element name="author" type="xs:string" use="required"/>
			        <xs:element name="date" type="xs:date" use="required"/>
			        <xs:element name="topic" type="xs:string" use="required"/>
         				<xs:element name="tags">
         					<xs:complexType>
      							<xs:sequence>
      								<xs:element name="tag" type="xs:string"/>
      							</xs:sequence>
      						</xs:complexType>
         				</xs:element>
         				<xs:element name="comms">
         					<xs:complexType>
      							<xs:sequence>
				      				<xs:element name="comm_author" type="xs:string" use="required"/>
				      				<xs:element name="comm_date" type="xs:date" use="required"/>
				      				<xs:element name="comm_text" type="xs:string" use="required"/>
      							</xs:sequence>
      						</xs:complexType>
         				</xs:element>
         				<xs:element name="title" type="xs:string"/>
         				<xs:element name="content" type="xs:string" use="required"/>
         			</xs:sequence>
  				</xs:complexType>
			</xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== MER1GO/MER1GO.github.io/sites/nure/lb5/blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE blog SYSTEM "blog.dtd">
<?xml-stylesheet type="text/xml" href="blog.xsl"?>
<blog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="blog.xsd">
	<post>
		<author>Jamie O`Conor</author>
		<date>17.10.1999</date>
		<topic>Food</topic>
		<tag>#Pizza</tag>
		<tag>#Cola</tag>
		<tag>#Burger</tag>
		<comms>
			<comm_author>James O`Conor</comm_author>
			<comm_date>18.10.1999</comm_date>
			<comm_text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A voluptas cumque explicabo enim, laboriosam nemo nobis! Expedita quod dolorem, mollitia!</comm_text>
		</comms>
		<title>Food of foods</title>
		<content>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat illo blanditiis, suscipit est impedit consequuntur nisi ab. Ullam quibusdam sapiente maiores, suscipit, expedita tempora sed ducimus ipsa totam ipsam, aperiam blanditiis, porro quos ut sunt libero laudantium necessitatibus commodi. Dolore officia nemo dicta pariatur at veniam quod tempora. Neque non, placeat, reprehenderit sunt minus ratione repellat suscipit animi ea impedit velit consequuntur minima qui ex esse, labore alias vero accusamus. Ullam dolorem eaque, a laborum laudantium dolore maxime deserunt nam saepe sapiente recusandae quod, inventore fuga harum odio? Porro molestias esse error, vel quae impedit est itaque debitis aliquam, recusandae tempore voluptate nesciunt voluptatibus molestiae voluptates ducimus pariatur incidunt cum eos, quo labore exercitationem! Porro necessitatibus quos illo nobis perspiciatis cupiditate magni voluptatibus animi perferendis vel minus, quod quaerat suscipit, dolorem, iste. Inventore voluptates similique iste, quod dolore nisi exercitationem asperiores, officiis atque quaerat? At temporibus iure et, repellat hic eius laborum natus voluptas, iste adipisci, ab fugit dolore architecto odio nesciunt! Corporis earum, assumenda similique, quas tenetur dolores voluptas hic voluptatum alias ex et nihil quod rem delectus sunt explicabo culpa odit error perferendis accusantium odio deleniti voluptatem in eos. Excepturi praesentium autem, placeat accusamus nisi. Ratione dolor, consequatur.</content>
	</post>

	<post>
		<author>James O`Conor</author>
		<date>18.10.1999</date>
		<topic>Cars</topic>
		
			<tag>#Car</tag>
			<tag>#Italia</tag>
			<tag>#Maserati</tag>
	
		<comms>
				<comm_author>Jamie O`Conor</comm_author>
				<comm_date>19.10.1999</comm_date>
				<comm_reply_to>James O`Connor</comm_reply_to>
				<comm_text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A voluptas cumque explicabo enim, laboriosam nemo nobis! Expedita quod dolorem, mollitia!</comm_text>
		</comms>
		<title>Car of Cars</title>
		<content>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam amet debitis itaque dolor libero tempora distinctio quia dolore, dicta aliquid quaerat quos eos sunt ipsa doloribus veniam voluptates quam praesentium voluptatibus facilis quidem! Excepturi esse aut voluptas quia, a magnam. Perferendis nesciunt iure porro provident soluta necessitatibus pariatur et odit ipsam, officia, delectus sunt rem fugit dolorem voluptates, odio laborum. Sint praesentium repellat nobis nemo exercitationem. Distinctio quisquam eveniet vel tenetur accusamus rerum numquam pariatur ab iusto, nobis officia fuga molestiae suscipit porro dolor! Praesentium debitis eius culpa omnis, ea voluptatum repudiandae quis eos laudantium saepe sunt odio fuga distinctio, repellat. Fugit molestiae, sit unde odit eligendi aliquam facilis quasi maiores rem! Cum rem tenetur quod, id, explicabo ducimus ab saepe modi! Error dicta commodi modi repellat deserunt eum, placeat aliquam quod molestiae hic accusamus rerum quaerat dolor minus facilis, voluptatem iste, omnis sint tempora aperiam. Error, quas velit. Porro quae similique rerum optio asperiores vitae voluptatem minima, maiores tempora eveniet facilis commodi inventore necessitatibus saepe esse dolore ipsum, itaque delectus. Labore architecto, sapiente, facere, nobis officia suscipit quae harum maiores nostrum rerum quod dolores, nemo reprehenderit? Dicta fugit sint facere est, eaque iusto temporibus quam, numquam quo dolore doloremque officia quisquam amet. Delectus, quidem est dicta! Fugiat laboriosam sunt, totam maxime a repellendus atque facere incidunt ullam possimus obcaecati, dignissimos officiis, alias commodi ea unde animi voluptatibus pariatur suscipit autem cupiditate. Amet at ut maiores vero quia eos laboriosam asperiores, blanditiis beatae quisquam placeat aspernatur tenetur nihil! Eius deleniti tempora, id placeat labore. Qui sed mollitia laudantium optio nihil atque tempore est libero quis cupiditate possimus maxime, illum quae nobis in vitae assumenda harum omnis voluptatibus sit amet hic temporibus alias. Consequatur, dicta! Amet atque ab, laboriosam autem voluptates nihil alias inventore ipsa, cum, veritatis accusamus ipsam facilis esse.
		</content>
	</post>

	<post>
		<author>Curtis Oliver</author>
		<date>19.10.1999</date>
		<topic>Coffee</topic>
		
			<tag>#Cappucino</tag>
			<tag>#Coffee</tag>
			<tag>#Coffein</tag>
			<tag>#Choice</tag>
	
		<comms>
				<comm_author>Jamie O`Conor</comm_author>
				<comm_date>19.10.1999</comm_date>
				<comm_reply_to>James O`Connor</comm_reply_to>
				<comm_text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, molestiae.</comm_text>
		</comms>
		<comms>
				<comm_author>James O`Connor</comm_author>
				<comm_date>19.10.1999</comm_date>
				<comm_reply_to>Jamie O`Conor</comm_reply_to>
				<comm_text>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium velit illo, obcaecati quod molestias. Illo.</comm_text>
		</comms>
		<title>Coffee on breakfast</title>
		<content>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa aliquam dolor voluptate perferendis excepturi repellendus corporis magnam minima exercitationem distinctio eligendi quia doloribus doloremque optio accusantium nisi iste quod illo similique alias dignissimos, omnis quos laborum tenetur. Rerum soluta suscipit, sunt dolore eligendi, voluptates blanditiis expedita qui ratione temporibus nulla, enim aspernatur voluptatem hic error! Temporibus earum, doloribus provident eligendi consectetur ipsam deleniti vitae unde, autem, architecto aperiam necessitatibus id eveniet. Incidunt nemo repellendus fuga vel quae dolorum, excepturi itaque magnam, suscipit, officiis tenetur nulla eveniet ea recusandae minus. Est adipisci tempore vel aspernatur, rem reiciendis corrupti corporis deserunt maxime, earum molestias repellat. Dolorum sit corrupti velit ducimus quibusdam quidem a dicta corporis repellendus eos nostrum, assumenda tempora voluptatem consequuntur placeat iusto, molestias quae explicabo dignissimos non architecto nulla recusandae expedita. Fugit autem, sunt sequi ratione architecto saepe reprehenderit, quisquam. Debitis unde fuga veritatis nemo a quos! Cumque neque consectetur quo obcaecati. Molestias ut tenetur ullam laborum dolor repudiandae officiis facere consequuntur eum. Excepturi maiores inventore ad ratione itaque. Animi mollitia sapiente aliquid maiores tempore adipisci nesciunt impedit dolores, at hic quisquam officiis laborum minima repellendus, asperiores itaque placeat odio quia ratione! Alias totam dolores sequi, doloremque asperiores, perferendis quod sit non, rem minus possimus! Dolor esse quod blanditiis enim ratione! Nisi tempore ipsa tenetur quam error, unde saepe impedit velit, omnis facilis, aliquam provident dolore temporibus. Nobis eos tenetur odit animi voluptas voluptatum, maiores ad quibusdam, laborum nostrum, corrupti, iste. Qui velit odio iste dolorum non quos perferendis quo tempora numquam, ipsa id explicabo cumque quidem impedit rerum consequatur repellat magnam vero suscipit voluptatibus voluptatem recusandae nihil neque dolorem. Reiciendis eaque omnis eum laboriosam natus cupiditate quas, corrupti eligendi consequuntur nulla. Ipsam eveniet obcaecati nulla praesentium commodi, animi inventore qui temporibus, laboriosam optio quae. Vel nemo obcaecati nam culpa, tempora nihil eius sapiente totam vero quo perferendis cupiditate quos, consequuntur quae sunt fugiat nostrum nobis voluptas dolores beatae dignissimos laborum, ratione voluptatum. Quaerat pariatur recusandae molestiae veritatis sapiente laborum, facere iste eaque inventore nobis quis est quam non alias, officia corporis cumque, odio praesentium totam itaque voluptate atque, repellat hic distinctio in! Consectetur ab esse aperiam! Earum, quos aspernatur. Optio iusto, soluta, deleniti velit dignissimos, expedita facilis molestias laborum, neque at atque! Enim ex, aliquid nemo a culpa, qui ipsam repellendus, perferendis, voluptate quaerat quae. Fugiat, ratione, sint. Impedit, accusantium sunt ex distinctio dolorum dolores sapiente tempora necessitatibus cupiditate.
		</content>
	</post>

	<post>
		<author>Ellionora O`Conor</author>
		<date>21.12.2119</date>
		<topic>Future</topic>
		
			<tag>#Future</tag>
			<tag>#NoPermission</tag>
			<tag>#ImTheOne</tag>
			<tag>#Amazing</tag>
	
		<comms>
				<comm_author></comm_author>
				<comm_date></comm_date>
				<comm_text></comm_text>
		</comms>
		<title>Post from the future</title>
		<content>
